.github/workflows/build_test.yml
.github/workflows/deploy.yml
Dockerfile

💚 Ci fix v.0.1.0

---

.github/workflows/deploy.yml

💚 Secrets option

---

.github/workflows/build_test.yml

💚 Hot fix ci

---

.vscode/settings.json
README.md
build.gradle
src/main/java/com/goorm/wordsketch/vocabulary/Vocabulary.java
src/main/java/com/goorm/wordsketch/vocabulary/VocabularyRepository.java
src/main/java/com/goorm/wordsketch/vocabulary/VocabularyType.java
src/main/resources/application.properties
src/main/resources/application.yml
src/test/java/com/goorm/wordsketch/unit/VocabularyRepositoryTest.java

> PostgreSQL(v16.2)에 스프링 서버를 연결 후 테스트
**관련 이슈**
resolves #9
**테스트 결과**

[INFRA] Spring Data JPA로 DB 연결 설정하기

---

.github/workflows/build_test.yml
build.gradle

💚 build test postgresSQL image changed v0.1.1

---

.github/workflows/deploy.yml

💚 Local db service add v0.1.1

---

src/main/java/com/goorm/wordsketch/service/VocabularyContentService.java

🎨 Few typo fix

---

src/main/java/com/goorm/wordsketch/batch/VocabularyContentSearchBatchConfiguration.java

🎨 Query upgrade

---

build.gradle
src/main/java/com/goorm/wordsketch/entity/Vocabulary.java
src/main/java/com/goorm/wordsketch/entity/VocabularyContent.java

🎨 Entity builder add

---

src/main/java/com/goorm/wordsketch/batch/VocabularyContentSearchBatchConfiguration.java
src/main/java/com/goorm/wordsketch/entity/Vocabulary.java
src/main/java/com/goorm/wordsketch/entity/VocabularyContent.java

🎨 Entity and localdatetime update

---

src/test/java/com/goorm/wordsketch/integration/batch/BatchIntegrationTestJobConfigurationTest.java

🔥 Ignore test code for merge

---

build.gradle
src/main/java/com/goorm/wordsketch/config/QuerydslConfiguration.java
src/main/java/com/goorm/wordsketch/config/VocabularyContentSearchBatchConfiguration.java
src/main/java/com/goorm/wordsketch/controller/VocabularyController.java
src/main/java/com/goorm/wordsketch/dto/GuestStudyContent.java
src/main/java/com/goorm/wordsketch/entity/Vocabulary.java
src/main/java/com/goorm/wordsketch/entity/VocabularyContent.java
src/main/java/com/goorm/wordsketch/repository/QVocabularyContentRepository.java
src/main/java/com/goorm/wordsketch/repository/QVocabularyContentRepositoryImpl.java
src/main/java/com/goorm/wordsketch/repository/QVocabularyRepository.java
src/main/java/com/goorm/wordsketch/repository/QVocabularyRepositoryImpl.java
src/main/java/com/goorm/wordsketch/repository/VocabularyContentRepository.java
src/main/java/com/goorm/wordsketch/repository/VocabularyRepository.java
src/main/java/com/goorm/wordsketch/service/VocabularyContentService.java
src/main/java/com/goorm/wordsketch/service/VocabularyService.java
src/test/java/com/goorm/wordsketch/unit/vocabulary/VocabularyRepositoryTest.java

guest controller, service, query update

🎨 Guest api update v0.1.3

---

build.gradle

⬆️ Upgrade build.gradle

---

.github/workflows/deploy.yml
Dockerfile
src/main/resources/application-prod.yml

💚 Ci automation fix

---

.github/workflows/build_test.yml
.github/workflows/deploy.yml
Dockerfile
build.gradle

remove secrets folder and checkout

⚰️ Remove dead code to ci v0.1.5

---

build.gradle
src/main/java/com/goorm/wordsketch/entity/VocabularyContent.java
src/main/resources/application-prod.yml
src/test/java/com/goorm/wordsketch/unit/vocabulary/VocabularyRepositoryTest.java

🐛 Db hot fix v0.1.6

---

build.gradle
src/main/resources/application-prod.yml

🔧 application-prod.yml v0.2.0

---

src/main/resources/application-prod.yml

Reverts PANTS-GOORM/BackEnd#41

Revert "🔧 Profiles.active 삭제 v0.2.0"

---

src/main/resources/application-prod.yml

⚰️ Remove dead code v0.2.1

---

build.gradle
src/main/resources/application-prod.yml

🐛 Fix prod bug v0.2.2

---

src/main/resources/application-prod.yml

🚀 Db hotfix v0.2.8
